INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (1, '大学英语', 'CS1001', '学习英语', '20', '张三');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (2, '高等数学', 'CS1002', '学习数学', '30', '李四');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (4, '线性代数', 'CS1004', '学习线代', '20', '孙六');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (5, 'Java', 'CS1005', '学习Java', '30', '好老师');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (6, 'C++', 'CS1006', '学习C++', '20', '坏老师');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (7, '概率论', 'CS1007', '学习概率论', '20', '刘七');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (8, '马原', 'CS1008', '学习马原', '16', '郑老师');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (9, '毛概', 'CS1009', '学习毛概', '20', '方老师');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (10, '计算机网络', 'CS1010', '学习网络', '30', '费老师');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (11, '数据结构', 'CS1011', '学习算法', '40', '李老师');
INSERT INTO `course` (`id`, `name`, `no`, `descr`, `times`, `teacher`) VALUES (12, '篮球', 'CS1012', '学习篮球', '30', '🐔老师');
